name: open_meteo_weather_app
description: Weather App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  chopper: ^8.0.3
  connectivity_plus: ^6.1.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.1
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  shared_preferences: ^2.3.3


dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  chopper_generator: ^8.0.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/

